# test_that("pdf2", {
#     b <- printFinitizedLogarithmicDensity(2,2)
#     expect_true(b == "1/2*theta^2*(2*theta^(-2)*log(1-theta)-2*theta^(-1)*(-1+theta)^(-1)-(-1+theta)^(-2))*log(1-theta)^(-1)"
#                 || b == "1/2*theta^2*(2*theta^(-2)-2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1)-log(1-theta)^(-1)*(-1+theta)^(-2))"
#                 || b == "-1/2*(log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)-2*theta^(-3)+2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2))*theta^3"
#                 || b == "1/2*(2*theta^(-2)-(-1+theta)^(-2)*log(1-theta)^(-1)-2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1))*theta^2"
#                 || b == "-1/2*theta^2*(log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2)+2*theta^(-1)*log(1-theta)^(-1)*(-1+theta)^(-1))"
#                 || b == "-1/2*((-1+theta)^(-2)*log(1-theta)^(-1)+2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)-2*theta^(-2))*theta^2"
#                 || b == "-1/2*((-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2)+2*theta^(-1)*(-1+theta)^(-1)*log(1-theta)^(-1))*theta^2"
#                 || b == "-1/2*(log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)+2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)-2*theta^(-3))*theta^3"
#                 || b == "-1/2*theta^2*(2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1)-2*theta^(-2)+log(1-theta)^(-1)*(-1+theta)^(-2))"
#                 || b == "1/2*theta^2*(2*theta^(-2)-2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)-log(1-theta)^(-1)*(-1+theta)^(-2))"
#                 || b == "1/2*(2*theta^(-2)-2*theta^(-1)*log(1-theta)^(-1)*(-1+theta)^(-1)-log(1-theta)^(-1)*(-1+theta)^(-2))*theta^2"
#                 || b == "1/2*(2*theta^(-3)-2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1))*theta^3"
#                 || b == "-1/2*(log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2)+2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1))*theta^2"
#                 || b == "1/2*theta^2*(2*theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-2)-2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1))"
#                 || b == "1/2*theta^2*(2*theta^(-2)*log(1-theta)-(-1+theta)^(-2)-2*theta^(-1)*(-1+theta)^(-1))*log(1-theta)^(-1)"
#                 || b == "1/2*(2*theta^(-2)*log(1-theta)-2*(-1+theta)^(-1)*theta^(-1)-(-1+theta)^(-2))*theta^2*log(1-theta)^(-1)"
#                 || b == "1/2*theta^2*log(1-theta)^(-1)*(2*theta^(-2)*log(1-theta)-2*theta^(-1)*(-1+theta)^(-1)-(-1+theta)^(-2))"
#                 || b == "1/2*(2*theta^(-3)*log(1-theta)-(-1+theta)^(-2)*theta^(-1)-2*(-1+theta)^(-1)*theta^(-2))*theta^3*log(1-theta)^(-1)"
#                 || b == "1/2*theta^2*log(1-theta)^(-1)*(2*theta^(-2)*log(1-theta)-2*(-1+theta)^(-1)*theta^(-1)-(-1+theta)^(-2))"
#                 || b == "-1/2*theta^2*log(1-theta)^(-1)*((-1+theta)^(-2)-2*theta^(-2)*log(1-theta)+2*theta^(-1)*(-1+theta)^(-1))"
#                 || b == "-1/2*(2*(-1+theta)^(-1)*theta^(-1)*log(1-theta)^(-1)+(-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2))*theta^2"
#                 || b == "-1/2*theta^2*((-1+theta)^(-2)*log(1-theta)^(-1)+2*theta^(-1)*(-1+theta)^(-1)*log(1-theta)^(-1)-2*theta^(-2))"
#                 || b == "-1/2*theta^2*(log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2)+2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1))"
#                 || b == "1/2*(2*theta^(-3)-log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)-2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2))*theta^3"
#                 || b == "1/2*theta^2*(2*theta^(-2)-(-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-1)*(-1+theta)^(-1)*log(1-theta)^(-1))"
#                 || b == "-1/2*theta^2*(log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2)+2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1))"
#                 || b == "1/2*theta^2*(2*theta^(-2)-2*theta^(-1)*log(1-theta)^(-1)*(-1+theta)^(-1)-log(1-theta)^(-1)*(-1+theta)^(-2))"
#                 || b == "-1/2*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)-2*theta^(-3)+log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1))*theta^3"
#                 || b == "-1/2*theta^2*((-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2)+2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1))"
#                 || b == "-1/2*theta^2*((-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2)+2*theta^(-1)*(-1+theta)^(-1)*log(1-theta)^(-1))"
#                 || b == "-1/2*theta^2*(2*(-1+theta)^(-1)*theta^(-1)-2*theta^(-2)*log(1-theta)+(-1+theta)^(-2))*log(1-theta)^(-1)"
#                 || b == "1/2*(2*theta^(-2)*log(1-theta)-2*theta^(-1)*(-1+theta)^(-1)-(-1+theta)^(-2))*theta^2*log(1-theta)^(-1)"
#                 || b == "-1/2*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)+log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2))*theta^2"
#                 || b == "1/2*theta^2*(2*theta^(-2)*log(1-theta)-2*(-1+theta)^(-1)*theta^(-1)-(-1+theta)^(-2))*log(1-theta)^(-1)"
#                 || b == "1/2*theta^2*log(1-theta)^(-1)*(2*theta^(-2)*log(1-theta)-(-1+theta)^(-2)-2*(-1+theta)^(-1)*theta^(-1))"
#                 || b == "-1/2*theta^2*(2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)-2*theta^(-2)+(-1+theta)^(-2)*log(1-theta)^(-1))"
#                 || b == "1/2*theta^3*(2*theta^(-3)-log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)-2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2))"
#                 || b == "-1/2*(log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2)+2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1))*theta^2"
#                 || b == "-1/2*((-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2)+2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1))*theta^2"
#                 || b == "-1/2*(2*(-1+theta)^(-1)*theta^(-1)-2*theta^(-2)*log(1-theta)+(-1+theta)^(-2))*theta^2*log(1-theta)^(-1)"
#                 || b == "-1/2*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)+log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)-2*theta^(-3))*theta^3"
#                 || b == "1/2*(2*theta^(-2)-2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)-(-1+theta)^(-2)*log(1-theta)^(-1))*theta^2"
#                 || b == "-1/2*(2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)+(-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2))*theta^2"
#                 || b == "1/2*(2*theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-1)*log(1-theta)^(-1)*(-1+theta)^(-1))*theta^2"
#                 || b == "1/2*(2*theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-2)-2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1))*theta^2"
#                 || b == "1/2*(2*theta^(-2)-2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1)-log(1-theta)^(-1)*(-1+theta)^(-2))*theta^2"
#                 || b == "-1/2*(log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2)+2*theta^(-1)*log(1-theta)^(-1)*(-1+theta)^(-1))*theta^2"
#                 || b == "-1/2*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)-2*theta^(-2)+log(1-theta)^(-1)*(-1+theta)^(-2))*theta^2"
#                 || b == "1/2*(2*theta^(-2)-(-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-1)*(-1+theta)^(-1)*log(1-theta)^(-1))*theta^2"
#                 || b == "1/2*(2*theta^(-3)-log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-2)-2*log(1-theta)^(-1)*theta^(-2)*(-1+theta)^(-1))*theta^3"
#                 || b == "1/2*theta^3*(2*theta^(-3)*log(1-theta)-2*(-1+theta)^(-1)*theta^(-2)-(-1+theta)^(-2)*theta^(-1))*log(1-theta)^(-1)"
#                 || b == "1/2*theta^3*(2*theta^(-3)*log(1-theta)-(-1+theta)^(-2)*theta^(-1)-2*(-1+theta)^(-1)*theta^(-2))*log(1-theta)^(-1)"
#                 || b == "1/2*(2*theta^(-2)-2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)-log(1-theta)^(-1)*(-1+theta)^(-2))*theta^2"
#                 || b == "-1/2*theta^2*(2*(-1+theta)^(-1)*theta^(-1)*log(1-theta)^(-1)+(-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2))"
#                 || b == "1/2*theta^3*(2*theta^(-3)-2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1))"
#                 || b == "1/2*(2*theta^(-2)-2*theta^(-1)*(-1+theta)^(-1)*log(1-theta)^(-1)-(-1+theta)^(-2)*log(1-theta)^(-1))*theta^2"
#                 || b == "1/2*(2*theta^(-3)*log(1-theta)-2*(-1+theta)^(-1)*theta^(-2)-(-1+theta)^(-2)*theta^(-1))*theta^3*log(1-theta)^(-1)"
#                 || b == "-1/2*(2*(-1+theta)^(-1)*theta^(-1)*log(1-theta)^(-1)-2*theta^(-2)+(-1+theta)^(-2)*log(1-theta)^(-1))*theta^2"
#                 || b == "-1/2*theta^2*(2*(-1+theta)^(-1)*theta^(-1)*log(1-theta)^(-1)-2*theta^(-2)+(-1+theta)^(-2)*log(1-theta)^(-1))"
#                 || b == "-1/2*(2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1)-2*theta^(-2)+log(1-theta)^(-1)*(-1+theta)^(-2))*theta^2"
#                 || b == "1/2*theta^3*log(1-theta)^(-1)*(2*theta^(-3)*log(1-theta)-(-1+theta)^(-2)*theta^(-1)-2*(-1+theta)^(-1)*theta^(-2))"
#                 || b == "-1/2*theta^2*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)+log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-2))"
#                 || b == "-1/2*((-1+theta)^(-2)*log(1-theta)^(-1)+2*theta^(-1)*(-1+theta)^(-1)*log(1-theta)^(-1)-2*theta^(-2))*theta^2"
#                 || b == "-1/2*theta^3*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)+log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)-2*theta^(-3))"
#                 || b == "1/2*theta^2*(2*theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-2)-2*theta^(-1)*log(1-theta)^(-1)*(-1+theta)^(-1))"
#                 || b == "1/2*(2*theta^(-3)-2*log(1-theta)^(-1)*theta^(-2)*(-1+theta)^(-1)-log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-2))*theta^3"
#                 || b == "1/2*(2*theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-2)-2*log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1))*theta^2"
#                 || b == "-1/2*theta^2*(2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)+(-1+theta)^(-2)*log(1-theta)^(-1)-2*theta^(-2))"
#                 || b == "1/2*theta^3*log(1-theta)^(-1)*(2*theta^(-3)*log(1-theta)-2*(-1+theta)^(-1)*theta^(-2)-(-1+theta)^(-2)*theta^(-1))"
#                 || b == "-1/2*(2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)-2*theta^(-2)+(-1+theta)^(-2)*log(1-theta)^(-1))*theta^2"
#                 || b == "-1/2*theta^3*(log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)-2*theta^(-3)+2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2))"
#                 || b == "-1/2*theta^2*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)-2*theta^(-2)+log(1-theta)^(-1)*(-1+theta)^(-2))"
#                 || b == "-1/2*theta^3*(log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1)+2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)-2*theta^(-3))"
#                 || b == "-1/2*theta^2*log(1-theta)^(-1)*(2*(-1+theta)^(-1)*theta^(-1)-2*theta^(-2)*log(1-theta)+(-1+theta)^(-2))"
#                 || b == "-1/2*theta^3*(2*(-1+theta)^(-1)*theta^(-2)-2*theta^(-3)*log(1-theta)+(-1+theta)^(-2)*theta^(-1))*log(1-theta)^(-1)"
#                 || b == "-1/2*theta^3*(2*log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-2)-2*theta^(-3)+log(1-theta)^(-1)*(-1+theta)^(-2)*theta^(-1))"
#                 || b == "1/2*theta^2*log(1-theta)^(-1)*(2*theta^(-2)*log(1-theta)-(-1+theta)^(-2)-2*theta^(-1)*(-1+theta)^(-1))"
#                 || b == "1/2*theta^2*(2*theta^(-2)-(-1+theta)^(-2)*log(1-theta)^(-1)-2*(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1))"
#                 || b == "1/2*(2*log(1-theta)*theta^(-3)-(-1+theta)^(-2)*theta^(-1)-2*(-1+theta)^(-1)*theta^(-2))*log(1-theta)^(-1)*theta^3"
#                 || b == "-1/2*(2*(-1+theta)^(-1)*theta^(-2)-2*theta^(-3)*log(1-theta)+(-1+theta)^(-2)*theta^(-1))*theta^3*log(1-theta)^(-1)" )
# })



test_that("pdf3", {
     capture.output(b <- printFinitizedLogarithmicDensity(2,3))
     expect_true(b == "0")
})


test_that("pdf1", {
    capture.output(b <- printFinitizedLogarithmicDensity(1,1))
    expect_true( b == "-theta*(theta^(-1)*log(1-theta)-(-1+theta)^(-1))*log(1-theta)^(-1)"
                || b == "-(theta^(-1)-(-1+theta)^(-1)*log(1-theta)^(-1))*theta"
                || b == "-(theta^(-2)*log(1-theta)-(-1+theta)^(-1)*theta^(-1))*theta^2*log(1-theta)^(-1)"
                || b == "theta*(log(1-theta)^(-1)*(-1+theta)^(-1)-theta^(-1))"
                || b == "-theta*(theta^(-1)-log(1-theta)^(-1)*(-1+theta)^(-1))"
                || b == "-log(1-theta)^(-1)*theta^2*(log(1-theta)*theta^(-2)-(-1+theta)^(-1)*theta^(-1))"
                || b == "((-1+theta)^(-1)*theta^(-1)-theta^(-2)*log(1-theta))*theta^2*log(1-theta)^(-1)"
                || b == "theta^2*(log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)-theta^(-2))"
                || b == "-(theta^(-1)-log(1-theta)^(-1)*(-1+theta)^(-1))*theta"
                || b == "(log(1-theta)^(-1)*(-1+theta)^(-1)-theta^(-1))*theta"
                || b == "-(theta^(-2)-(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1))*theta^2"
                || b == "theta*((-1+theta)^(-1)-theta^(-1)*log(1-theta))*log(1-theta)^(-1)"
                || b == "theta*((-1+theta)^(-1)*log(1-theta)^(-1)-theta^(-1))"
                || b == "((-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)-theta^(-2))*theta^2"
                || b == "-log(1-theta)^(-1)*(log(1-theta)*theta^(-2)-(-1+theta)^(-1)*theta^(-1))*theta^2"
                || b == "-(theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1))*theta^2"
                || b == "-theta^2*log(1-theta)^(-1)*(theta^(-2)*log(1-theta)-theta^(-1)*(-1+theta)^(-1))"
                || b == "(log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1)-theta^(-2))*theta^2"
                || b == "((-1+theta)^(-1)*log(1-theta)^(-1)-theta^(-1))*theta"
                || b == "-theta*(theta^(-1)-(-1+theta)^(-1)*log(1-theta)^(-1))"
                || b == "-(log(1-theta)*theta^(-2)-(-1+theta)^(-1)*theta^(-1))*log(1-theta)^(-1)*theta^2"
                || b == "-theta*log(1-theta)^(-1)*(theta^(-1)*log(1-theta)-(-1+theta)^(-1))"
                || b == "theta^2*((-1+theta)^(-1)*theta^(-1)-theta^(-2)*log(1-theta))*log(1-theta)^(-1)"
                || b == "-theta^2*(theta^(-2)-log(1-theta)^(-1)*theta^(-1)*(-1+theta)^(-1))"
                || b == "theta*log(1-theta)^(-1)*((-1+theta)^(-1)-theta^(-1)*log(1-theta))"
                || b == "-theta^2*(theta^(-2)-log(1-theta)^(-1)*(-1+theta)^(-1)*theta^(-1))"
                || b == "-theta^2*log(1-theta)^(-1)*(theta^(-2)*log(1-theta)-(-1+theta)^(-1)*theta^(-1))"
                || b == "theta^2*log(1-theta)^(-1)*((-1+theta)^(-1)*theta^(-1)-theta^(-2)*log(1-theta))"
                || b == "((-1+theta)^(-1)*theta^(-1)-log(1-theta)*theta^(-2))*log(1-theta)^(-1)*theta^2"
                || b == "((-1+theta)^(-1)-theta^(-1)*log(1-theta))*theta*log(1-theta)^(-1)"
                || b == "theta^2*((-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1)-theta^(-2))"
                || b == "-theta^2*(theta^(-2)*log(1-theta)-(-1+theta)^(-1)*theta^(-1))*log(1-theta)^(-1)"
                || b == "-theta^2*(theta^(-2)-(-1+theta)^(-1)*log(1-theta)^(-1)*theta^(-1))")
})
