# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Generate string representation of a finitized probability density function
NULL

#' Compute the probability mass function of a finitized distribution
NULL

#' Generate random values from a finitized distribution
NULL

#' Compute the symbolic expression for \code{pdf(n - 1)} used in MFPS bounds
NULL

#' Return internal identifier for the Poisson distribution
NULL

#' Return internal identifier for the Negative Binomial distribution
NULL

#' Return internal identifier for the Logarithmic distribution
NULL

#' Check symbolic equivalence of two expressions using GiNaC
NULL

c_printDensity <- function(n, val, params, dtype, latex = FALSE) {
    .Call('_finitization_c_printDensity', PACKAGE = 'finitization', n, val, params, dtype, latex)
}

c_d <- function(n, val, params, dtype) {
    .Call('_finitization_c_d', PACKAGE = 'finitization', n, val, params, dtype)
}

rvalues <- function(n, params, no, dtype) {
    .Call('_finitization_rvalues', PACKAGE = 'finitization', n, params, no, dtype)
}

MFPS_pdf <- function(n, params, dtype) {
    .Call('_finitization_MFPS_pdf', PACKAGE = 'finitization', n, params, dtype)
}

getPoissonType <- function() {
    .Call('_finitization_getPoissonType', PACKAGE = 'finitization')
}

getNegativeBinomialType <- function() {
    .Call('_finitization_getNegativeBinomialType', PACKAGE = 'finitization')
}

getBinomialType <- function() {
    .Call('_finitization_getBinomialType', PACKAGE = 'finitization')
}

getLogarithmicType <- function() {
    .Call('_finitization_getLogarithmicType', PACKAGE = 'finitization')
}

check_symbolic_equivalence <- function(expr1_str, expr2_str) {
    .Call('_finitization_check_symbolic_equivalence', PACKAGE = 'finitization', expr1_str, expr2_str)
}

