# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @param n
#' @param theta
#' @param no
#' @export
rpois <- function(n, theta, no) {
    .Call('_finitization_rpois', PACKAGE = 'finitization', n, theta, no)
}

#' @param n
#' @param theta
#' @param val
#' @export
c_dpois <- function(n, theta, val) {
    .Call('_finitization_c_dpois', PACKAGE = 'finitization', n, theta, val)
}

#' @param n
#' @param theta
#' @param val
#' @export
c_printFinitizedPoissonDensity <- function(n, val, latex = FALSE) {
    .Call('_finitization_c_printFinitizedPoissonDensity', PACKAGE = 'finitization', n, val, latex)
}

